package model;

public class Student{

    private int id;
    private String name;
    private int marks;

    //Constructor for insert (id auto-generated by DB)
    public Student(String name, int marks) {
        this.name = name;
        this.marks = marks;
    }

    //Constructor for select (id comes from DB)
    public Student(int id, String name, int marks) {
        this.id = id;
        this.name = name;
        this.marks = marks;
    }

    //Getters
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getMarks() {
        return marks;
    }
}